import type { ConsentBudget, FieldName } from '../src/types.js';

/**
 * Fifty people who would plausibly hand their dating life to an agent.
 *
 * The bar was not "sounds like a dating profile" — it was "this person is
 * busy, delegates, and would rather their agent did the first twenty messages".
 * So: shift workers, founders, researchers, contractors, people on call, people
 * who travel. Deliberately not fifty engineers; an agent-to-agent protocol is
 * only interesting if the people are not interchangeable.
 *
 * Each has one specific detail that could not be generated from a template, and
 * a dealbreaker that is an actual dealbreaker rather than a preference. The
 * consent budgets vary on purpose — a demo where everyone runs the defaults
 * never shows the gate doing anything.
 */

export interface Persona {
  displayName: string;
  fields: Partial<Record<FieldName, string>>;
  budget?: Partial<ConsentBudget>;
}

const B = (
  levels: [ConsentBudget['levels']['L0'], ConsentBudget['levels']['L1'], ConsentBudget['levels']['L2'], ConsentBudget['levels']['L3']],
  neverShare: string[] = [],
  forwardness = 3,
): Partial<ConsentBudget> => ({
  levels: { L0: levels[0], L1: levels[1], L2: levels[2], L3: levels[3] },
  neverShare,
  forwardness,
});

export const PERSONAS: Persona[] = [
  {
    displayName: 'Maya Okonjo',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'warm but blunt, decides fast and rarely relitigates',
      interests: 'bouldering, secondhand bookshops, Ethiopian food',
      area: 'Mission',
      goodSaturday: 'gym at eight, then reading in Dolores until it gets cold',
      hobbies: 'stuck at V5 for eight months and taking it personally',
      tastes: 'krautrock, Tarkovsky, anything fermented',
      lookingFor: 'someone with their own thing going on, not a project',
      ageBand: 'late 20s',
      availability: 'weeknights after 7, Saturdays before noon',
      neighborhood: 'Valencia & 21st',
      dealbreakers: 'people who say they love hiking and mean one trail, once, in 2019',
      name: 'Maya Okonjo',
      job: 'infrastructure engineer',
      contact: '@mayaok',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['my employer']),
  },
  {
    displayName: 'Daniel Reyes',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'quiet, dry, listens more than he talks',
      interests: 'cycling, film photography, cooking for too many people',
      area: 'Oakland',
      goodSaturday: 'ride to Marin, develop a roll, feed whoever turns up',
      hobbies: 'restoring a 1987 Bridgestone he will never finish',
      tastes: 'jazz he pretends to understand, very spicy food',
      lookingFor: 'someone who finishes things, or at least admires the attempt',
      ageBand: 'early 30s',
      availability: 'most evenings, Sundays are darkroom days',
      neighborhood: 'Temescal',
      dealbreakers: 'rudeness to service staff, no exceptions',
      name: 'Daniel Reyes',
      job: 'pediatric nurse',
      contact: '@danreyes',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Priya Raghunathan',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'high energy, talks with her hands, always mid-project',
      interests: 'ceramics, long walks, arguing about architecture',
      area: 'Berkeley',
      goodSaturday: 'farmers market then the studio until my hands hurt',
      hobbies: 'wheel-throwing badly and refusing to take a class',
      tastes: 'Carnatic music, brutalist buildings, sour beer',
      lookingFor: 'someone curious enough to be dragged to a building tour',
      ageBand: 'early 30s',
      availability: 'weekday evenings, studio Sundays',
      neighborhood: 'North Berkeley',
      dealbreakers: 'people who have no opinions about anything',
      name: 'Priya Raghunathan',
      job: 'structural engineer',
      contact: '@priyabuilds',
    },
    budget: B(['free', 'free', 'ask', 'never']),
  },
  {
    displayName: 'Tom Whitfield',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'unhurried, deeply uncool about his hobbies, fine with it',
      interests: 'birding, brewing, long drives with no destination',
      area: 'Sunset',
      goodSaturday: 'up at five for the tide, home by noon, nap',
      hobbies: 'keeps a spreadsheet of every bird seen since 2011',
      tastes: 'bluegrass, westerns, a specific brand of pickle',
      lookingFor: 'someone who does not need every weekend to be an event',
      ageBand: 'late 30s',
      availability: 'weekends mostly, weeknights are early',
      neighborhood: 'Outer Sunset',
      dealbreakers: 'anyone who calls a hobby a waste of time',
      name: 'Tom Whitfield',
      job: 'high school biology teacher',
      contact: '@twhitbirds',
    },
    budget: B(['free', 'free', 'free', 'ask']),
  },
  {
    displayName: 'Nadia Haddad',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'fast, funny, allergic to small talk and says so early',
      interests: 'stand-up, weightlifting, true crime podcasts she knows are bad',
      area: 'SoMa',
      goodSaturday: 'lift, then an open mic where I do not perform',
      hobbies: 'deadlift PR is a personality trait at this point',
      tastes: 'hip hop, horror films, extremely strong coffee',
      lookingFor: 'someone who can take a joke and return one',
      ageBand: 'late 20s',
      availability: 'after 8 most nights, gym in the mornings',
      neighborhood: 'near Rincon Hill',
      dealbreakers: 'defensiveness — if a light joke lands badly, we are done',
      name: 'Nadia Haddad',
      job: 'ER physician assistant',
      contact: '@nadiahdd',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['where i work']),
  },
  {
    displayName: 'Chris Vandermeer',
    fields: {
      gender: 'man',
      seeking: 'men',
      vibe: 'methodical, wry, notices everything and mentions half of it',
      interests: 'woodworking, sailing, restoring hand tools',
      area: 'Alameda',
      goodSaturday: 'sail if there is wind, shop if there is not',
      hobbies: 'rehabilitating rusted hand planes he finds at estate sales',
      tastes: 'Bach, Le Carré, whisky he cannot afford',
      lookingFor: 'someone patient, and honest earlier than is comfortable',
      ageBand: 'early 40s',
      availability: 'weekends, and Wednesday evenings',
      neighborhood: 'West End',
      dealbreakers: 'anyone still litigating an ex in the first month',
      name: 'Chris Vandermeer',
      job: 'furniture maker',
      contact: '@vandermade',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Amara Nwosu',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'measured in public, very silly once she trusts you',
      interests: 'contemporary dance, poetry, cold water swimming',
      area: 'Hayes Valley',
      goodSaturday: 'ocean swim at seven, then absolutely nothing',
      hobbies: 'swims at Aquatic Park year round and will not shut up about it',
      tastes: 'Afrobeat, Ocean Vuong, oysters',
      lookingFor: 'something serious, and is done pretending otherwise',
      ageBand: 'early 30s',
      availability: 'evenings except Tuesday rehearsal',
      neighborhood: 'near Patricia Green',
      dealbreakers: 'vagueness about what they want',
      name: 'Amara Nwosu',
      job: 'immigration lawyer',
      contact: '@amaraswims',
    },
    budget: B(['free', 'ask', 'ask', 'ask'], ['my firm']),
  },
  {
    displayName: 'Jonas Berg',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'calm to the point of being hard to read, then suddenly warm',
      interests: 'mycology, trail running, fermentation',
      area: 'Marin',
      goodSaturday: 'long run in the headlands, forage on the way back',
      hobbies: 'can identify about forty mushrooms and eats maybe six',
      tastes: 'ambient, Tarkovsky again, koji everything',
      lookingFor: 'someone comfortable with quiet',
      ageBand: 'mid 30s',
      availability: 'flexible, works odd hours',
      neighborhood: 'Mill Valley',
      dealbreakers: 'needing constant reassurance over text',
      name: 'Jonas Berg',
      job: 'wildlife biologist',
      contact: '@jonasfungi',
    },
    budget: B(['free', 'free', 'ask', 'never']),
  },
  {
    displayName: 'Rina Matsuda',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'precise, funny in a way that takes a second to land',
      interests: 'chess, textile design, bad reality TV',
      area: 'Japantown',
      goodSaturday: 'chess in the park, fabric store, then trash television',
      hobbies: 'rated 1650 and mildly furious about it',
      tastes: 'city pop, Ozu, konbini egg sandwiches',
      lookingFor: 'someone who will lose at chess without sulking',
      ageBand: 'late 20s',
      availability: 'weeknights, weekends are family time',
      neighborhood: 'near Peace Plaza',
      dealbreakers: 'condescension, especially the friendly kind',
      name: 'Rina Matsuda',
      job: 'UX researcher',
      contact: '@rinaplays',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Marcus Bell',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'gregarious, remembers names, genuinely likes strangers',
      interests: 'basketball, barbecue, live music',
      area: 'Bayview',
      goodSaturday: 'pickup game, then smoking a brisket nobody asked for',
      hobbies: 'runs a Sunday league nobody appointed him to run',
      tastes: 'funk, Elmore Leonard, bourbon',
      lookingFor: 'someone who likes being around people as much as he does',
      ageBand: 'late 30s',
      availability: 'evenings, but Sundays are league days',
      neighborhood: 'near Third Street',
      dealbreakers: 'flaking twice',
      name: 'Marcus Bell',
      job: 'union electrician',
      contact: '@marcusbell',
    },
    budget: B(['free', 'free', 'free', 'ask']),
  },
  {
    displayName: 'Elena Vasquez',
    fields: {
      gender: 'woman',
      seeking: 'anyone',
      vibe: 'observant, a bit guarded, extremely loyal once in',
      interests: 'printmaking, cold brew, urban foraging',
      area: 'Excelsior',
      goodSaturday: 'studio in the morning, plant shopping in the afternoon',
      hobbies: 'linocut prints she gives away and never sells',
      tastes: 'boleros, Almodóvar, mole',
      lookingFor: 'slow, and real',
      ageBand: 'early 30s',
      availability: 'weekends, weeknights are unpredictable',
      neighborhood: 'near Persia Triangle',
      dealbreakers: 'anyone who treats her job as a stepping stone conversation',
      name: 'Elena Vasquez',
      job: 'public defender',
      contact: '@elenaprints',
    },
    budget: B(['free', 'ask', 'ask', 'never'], ['my caseload']),
  },
  {
    displayName: 'Sam Okafor',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'earnest, curious, asks better questions than he answers',
      interests: 'astronomy, board games, long bus rides',
      area: 'Richmond',
      goodSaturday: 'game night that starts at two and ends at midnight',
      hobbies: 'grinds a telescope mirror by hand, four years in',
      tastes: 'prog rock, Le Guin, dumplings',
      lookingFor: 'someone who will let a hobby get weird',
      ageBand: 'mid 30s',
      availability: 'weekends, clear nights are non-negotiable',
      neighborhood: 'Inner Richmond',
      dealbreakers: 'incuriosity',
      name: 'Sam Okafor',
      job: 'data scientist',
      contact: '@samstars',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Hannah Lieberman',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'direct, warm, will tell you what she thinks before you ask',
      interests: 'opera, swimming, restaurant openings',
      area: 'Nob Hill',
      goodSaturday: 'swim, then eat somewhere new and be honest about it',
      hobbies: 'keeps a ranked list of every bowl of ramen in the city',
      tastes: 'Verdi, Nora Ephron, natural wine',
      lookingFor: 'someone decisive — she is tired of picking the restaurant',
      ageBand: 'late 30s',
      availability: 'weeknights after 7',
      neighborhood: 'near Huntington Park',
      dealbreakers: 'indecision dressed up as easygoingness',
      name: 'Hannah Lieberman',
      job: 'hospital administrator',
      contact: '@hannahleib',
    },
    budget: B(['free', 'free', 'ask', 'ask'], [], 4),
  },
  {
    displayName: 'Kofi Mensah',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'steady, funny, hard to rattle',
      interests: 'football, cooking, mentoring',
      area: 'Daly City',
      goodSaturday: 'match in the morning, cook all afternoon, people over',
      hobbies: 'perfecting jollof and taking regional criticism seriously',
      tastes: 'highlife, Adichie, plantain in any form',
      lookingFor: 'a partner, plainly stated',
      ageBand: 'early 40s',
      availability: 'evenings, Saturday mornings are football',
      neighborhood: 'near Serramonte',
      dealbreakers: 'anyone unkind about family',
      name: 'Kofi Mensah',
      job: 'civil engineer',
      contact: '@kofimen',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Ivy Chen',
    fields: {
      gender: 'woman',
      seeking: 'women',
      vibe: 'sharp, quick, slightly impatient and working on it',
      interests: 'rock climbing, startups, tea',
      area: 'Potrero Hill',
      goodSaturday: 'climb in the morning, work on something in the afternoon',
      hobbies: 'brings her own tea to restaurants, unapologetically',
      tastes: 'techno, Chiang, single-origin oolong',
      lookingFor: 'someone building something, anything',
      ageBand: 'late 20s',
      availability: 'early mornings and late nights, nothing in between',
      neighborhood: 'near 18th & Texas',
      dealbreakers: 'complaining about a situation for months without changing it',
      name: 'Ivy Chen',
      job: 'founder, two people and a server',
      contact: '@ivybuilds',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['my company'], 5),
  },
  {
    displayName: 'Ben Ostrowski',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'soft-spoken, thoughtful, funnier over text than in person',
      interests: 'vinyl, cooking, cold weather camping',
      area: 'Glen Park',
      goodSaturday: 'record store, then something slow on the stove',
      hobbies: 'owns a tent rated to -20F and has used it twice',
      tastes: 'shoegaze, Murakami, sourdough he keeps alive',
      lookingFor: 'someone who is fine with a quiet Friday',
      ageBand: 'mid 30s',
      availability: 'weekends, some weeknights',
      neighborhood: 'near Glen Canyon',
      dealbreakers: 'someone who needs to be out every night',
      name: 'Ben Ostrowski',
      job: 'archivist',
      contact: '@benarchive',
    },
    budget: B(['free', 'free', 'ask', 'never']),
  },
  {
    displayName: 'Zainab Ali',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'poised, watchful, extremely funny once comfortable',
      interests: 'calligraphy, distance running, museums',
      area: 'Fremont',
      goodSaturday: 'long run, then a museum with no plan',
      hobbies: 'practises Thuluth script an hour a day and shows nobody',
      tastes: 'qawwali, Ishiguro, cardamom in everything',
      lookingFor: 'someone serious about building a life',
      ageBand: 'early 30s',
      availability: 'weekends, weeknights after 8',
      neighborhood: 'Irvington',
      dealbreakers: 'anyone who treats faith as a debate topic',
      name: 'Zainab Ali',
      job: 'clinical pharmacist',
      contact: '@zainabruns',
    },
    budget: B(['free', 'ask', 'ask', 'ask'], ['my family']),
  },
  {
    displayName: 'Theo Lindqvist',
    fields: {
      gender: 'man',
      seeking: 'men',
      vibe: 'blunt, warm underneath, no interest in small talk',
      interests: 'sailing, carpentry, cold plunges',
      area: 'Sausalito',
      goodSaturday: 'on the water by seven, tools out by two',
      hobbies: 'building a dinghy in a garage that is too small for it',
      tastes: 'Nordic folk, Knausgård, black coffee',
      lookingFor: 'someone straightforward',
      ageBand: 'early 40s',
      availability: 'most days, works from home',
      neighborhood: 'near the marina',
      dealbreakers: 'game-playing about interest level',
      name: 'Theo Lindqvist',
      job: 'naval architect',
      contact: '@theosails',
    },
    budget: B(['free', 'free', 'free', 'ask']),
  },
  {
    displayName: 'Grace Mbeki',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'bright, generous, terrible at hiding what she thinks',
      interests: 'gardening, choir, baking',
      area: 'Vallejo',
      goodSaturday: 'garden until it is hot, bake until it is not',
      hobbies: 'sings alto in a choir that meets in a church basement',
      tastes: 'gospel, Baldwin, anything with cardamom',
      lookingFor: 'someone kind, and around',
      ageBand: 'late 30s',
      availability: 'evenings, Sunday mornings are choir',
      neighborhood: 'near the waterfront',
      dealbreakers: 'unreliability',
      name: 'Grace Mbeki',
      job: 'midwife',
      contact: '@gracegrows',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Lucas Ferreira',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'playful, restless, extremely present when he is present',
      interests: 'surfing, music production, motorbikes',
      area: 'Pacifica',
      goodSaturday: 'dawn patrol, then studio until it gets dark',
      hobbies: 'makes beats nobody hears and is genuinely fine with that',
      tastes: 'baile funk, Sorrentino, açaí done properly',
      lookingFor: 'someone who will get in the water at least once',
      ageBand: 'late 20s',
      availability: 'afternoons and evenings, mornings are surf',
      neighborhood: 'Linda Mar',
      dealbreakers: 'contempt for anything he loves',
      name: 'Lucas Ferreira',
      job: 'sound engineer',
      contact: '@lucasmakes',
    },
    budget: B(['free', 'free', 'ask', 'ask'], [], 4),
  },
  {
    displayName: 'Sarah Kaminski',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'analytical, dry, kinder than she first appears',
      interests: 'birdwatching, crosswords, long train journeys',
      area: 'Palo Alto',
      goodSaturday: 'a walk with binoculars and the Saturday crossword',
      hobbies: 'has done the Saturday crossword in pen since 2014',
      tastes: 'chamber music, Sebald, marmalade',
      lookingFor: 'someone she can be quiet with',
      ageBand: 'early 40s',
      availability: 'weekends, weeknights are late',
      neighborhood: 'Professorville',
      dealbreakers: 'people who fill every silence',
      name: 'Sarah Kaminski',
      job: 'research scientist',
      contact: '@skaminski',
    },
    budget: B(['free', 'ask', 'ask', 'ask'], ['my lab'], 2),
  },
  {
    displayName: 'Andre Dupont',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'charming, a little theatrical, self-aware about it',
      interests: 'theatre, wine, cycling',
      area: 'Castro',
      goodSaturday: 'a ride in the morning, a matinee in the afternoon',
      hobbies: 'has seen the same play in four different productions',
      tastes: 'Sondheim, Baldwin, Beaujolais',
      lookingFor: 'someone with opinions and the patience to hear his',
      ageBand: 'late 30s',
      availability: 'weeknights, weekends often booked',
      neighborhood: 'near Duboce Park',
      dealbreakers: 'incuriosity about art of any kind',
      name: 'Andre Dupont',
      job: 'theatre director',
      contact: '@andredirects',
    },
    budget: B(['free', 'free', 'ask', 'ask'], [], 4),
  },
  {
    displayName: 'Mei Lin Tan',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'gentle, observant, quietly stubborn',
      interests: 'tea ceremony, hiking, watercolour',
      area: 'Millbrae',
      goodSaturday: 'a trail early, painting badly by the afternoon',
      hobbies: 'paints the same hill every month to see it change',
      tastes: 'guqin, Ishiguro, dan tat',
      lookingFor: 'someone steady',
      ageBand: 'mid 30s',
      availability: 'weekends, weeknight evenings',
      neighborhood: 'near the station',
      dealbreakers: 'raised voices',
      name: 'Mei Lin Tan',
      job: 'occupational therapist',
      contact: '@meilinpaints',
    },
    budget: B(['free', 'free', 'ask', 'never']),
  },
  {
    displayName: 'Owen Brady',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'chatty, self-deprecating, secretly very competent',
      interests: 'football, pub quizzes, hillwalking',
      area: 'Inner Sunset',
      goodSaturday: 'match at six in the morning, walk it off after',
      hobbies: 'captains a pub quiz team that has never won',
      tastes: 'Britpop, Rooney, a proper pint',
      lookingFor: 'someone who will come to the quiz and not take it seriously',
      ageBand: 'early 30s',
      availability: 'evenings, Tuesdays are quiz night',
      neighborhood: 'near Irving',
      dealbreakers: 'meanness disguised as banter',
      name: 'Owen Brady',
      job: 'paramedic',
      contact: '@owenquiz',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Fatima Zahra',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'composed, incisive, laughs suddenly and loudly',
      interests: 'architecture, cycling, cooking',
      area: 'Emeryville',
      goodSaturday: 'ride across the bridge, cook something ambitious',
      hobbies: 'photographs staircases in every building she enters',
      tastes: 'Gnawa, Calvino, preserved lemon',
      lookingFor: 'someone with a long attention span',
      ageBand: 'early 30s',
      availability: 'weeknights, weekends variable',
      neighborhood: 'near the marina',
      dealbreakers: 'people who cannot be alone',
      name: 'Fatima Zahra',
      job: 'architect',
      contact: '@fatimabuilds',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Peter Nakashima',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'deadpan, generous, hard to impress and honest about it',
      interests: 'knife making, ramen, kendo',
      area: 'San Mateo',
      goodSaturday: 'forge in the morning, kendo in the evening',
      hobbies: 'makes kitchen knives and gives them to people who cook',
      tastes: 'city pop, Kurosawa, tonkotsu that took two days',
      lookingFor: 'someone who takes something seriously',
      ageBand: 'early 40s',
      availability: 'weekends, Wednesday evenings are practice',
      neighborhood: 'near downtown',
      dealbreakers: 'dabbling in everything, committing to nothing',
      name: 'Peter Nakashima',
      job: 'mechanical engineer',
      contact: '@peterforge',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Chloe Bennett',
    fields: {
      gender: 'woman',
      seeking: 'anyone',
      vibe: 'bubbly on the surface, quite serious underneath',
      interests: 'ballet, museums, pastry',
      area: 'Cow Hollow',
      goodSaturday: 'barre class, then a museum, then a very good croissant',
      hobbies: 'took up adult ballet at 29 and goes four times a week',
      tastes: 'Chopin, Didion, laminated dough',
      lookingFor: 'someone ambitious who is not a workaholic about it',
      ageBand: 'early 30s',
      availability: 'evenings except class nights',
      neighborhood: 'near Union Street',
      dealbreakers: 'people who mock earnestness',
      name: 'Chloe Bennett',
      job: 'management consultant',
      contact: '@chloedances',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['my client']),
  },
  {
    displayName: 'Hassan Karim',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'thoughtful, slow to open up, very funny once he does',
      interests: 'chess, poetry, long drives',
      area: 'Union City',
      goodSaturday: 'chess club in the morning, drive somewhere with no plan',
      hobbies: 'memorises Ghalib couplets and deploys them badly',
      tastes: 'ghazals, Faiz, kebab from one specific place',
      lookingFor: 'something lasting',
      ageBand: 'mid 30s',
      availability: 'weekends, weeknights after 8',
      neighborhood: 'near Alvarado',
      dealbreakers: 'dishonesty of any size',
      name: 'Hassan Karim',
      job: 'accountant',
      contact: '@hassanchess',
    },
    budget: B(['free', 'ask', 'ask', 'ask']),
  },
  {
    displayName: 'Julia Sokolova',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'intense, warm, no patience for pretence',
      interests: 'violin, mountaineering, Russian novels',
      area: 'Twin Peaks',
      goodSaturday: 'practise for two hours, then climb something',
      hobbies: 'plays in an amateur orchestra and takes it very seriously',
      tastes: 'Shostakovich, Tolstoy, black bread',
      lookingFor: 'someone with a spine',
      ageBand: 'late 30s',
      availability: 'weekends, Thursday is rehearsal',
      neighborhood: 'near Portola',
      dealbreakers: 'passivity',
      name: 'Julia Sokolova',
      job: 'orthopaedic surgeon',
      contact: '@juliaplays',
    },
    budget: B(['free', 'free', 'ask', 'never'], ['my hospital']),
  },
  {
    displayName: 'Nate Coleman',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'easygoing, curious, genuinely likes being wrong',
      interests: 'podcasts, running, home espresso',
      area: 'Noe Valley',
      goodSaturday: 'run, then dial in a shot for an hour',
      hobbies: 'has spent more on a grinder than on his bike',
      tastes: 'indie folk, Gladwell he argues with, light roast',
      lookingFor: 'someone to build a routine with',
      ageBand: 'early 30s',
      availability: 'mornings and evenings',
      neighborhood: 'near 24th Street',
      dealbreakers: 'cynicism as a personality',
      name: 'Nate Coleman',
      job: 'product manager',
      contact: '@natebrews',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Adaeze Obi',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'commanding, funny, does not do lukewarm',
      interests: 'dance, entrepreneurship, sneakers',
      area: 'Downtown Oakland',
      goodSaturday: 'dance class, then working on the business',
      hobbies: 'runs an Afrobeats class on Sunday mornings',
      tastes: 'Burna Boy, Adichie, suya',
      lookingFor: 'someone with drive who is not competitive with her',
      ageBand: 'early 30s',
      availability: 'evenings, Sundays are class',
      neighborhood: 'near Lake Merritt',
      dealbreakers: 'anyone threatened by ambition',
      name: 'Adaeze Obi',
      job: 'founder, direct-to-consumer skincare',
      contact: '@adaezemoves',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['my brand'], 5),
  },
  {
    displayName: 'Simon Fletcher',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'reserved, precise, unexpectedly silly',
      interests: 'model trains, hiking, history',
      area: 'Walnut Creek',
      goodSaturday: 'a long hike, then an hour on the layout',
      hobbies: 'building an N-scale layout of a line that closed in 1962',
      tastes: 'classical, Mantel, real ale',
      lookingFor: 'someone who will let him be strange about a hobby',
      ageBand: 'mid 40s',
      availability: 'weekends, weeknights after 7',
      neighborhood: 'near downtown',
      dealbreakers: 'embarrassment about him in front of others',
      name: 'Simon Fletcher',
      job: 'actuary',
      contact: '@simonrails',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Leila Ahmadi',
    fields: {
      gender: 'non-binary',
      seeking: 'anyone',
      vibe: 'incisive, warm, asks the question everyone is avoiding',
      interests: 'documentary film, swimming, Persian cooking',
      area: 'Berkeley',
      goodSaturday: 'pool at seven, then editing until it is dark',
      hobbies: 'has been cutting the same documentary for three years',
      tastes: 'Kiarostami, Forugh, saffron used properly',
      lookingFor: 'someone with something they care about too much',
      ageBand: 'mid 30s',
      availability: 'evenings, weekends often editing',
      neighborhood: 'near Ashby',
      dealbreakers: 'indifference',
      name: 'Leila Ahmadi',
      job: 'documentary editor',
      contact: '@leilacuts',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['my film']),
  },
  {
    displayName: 'Danny Kowalski',
    fields: {
      gender: 'non-binary',
      seeking: 'anyone',
      vibe: 'loud, kind, absolutely no filter',
      interests: 'hockey, grilling, restoring cars',
      area: 'San Bruno',
      goodSaturday: 'rink at six, garage after, beer by four',
      hobbies: 'rebuilding a Camaro that has not run since 2019',
      tastes: 'classic rock, Elmore Leonard, anything smoked',
      lookingFor: 'someone straightforward who says what they mean',
      ageBand: 'late 30s',
      availability: 'weekends, weeknights after 6',
      neighborhood: 'near the parkway',
      dealbreakers: 'passive aggression',
      name: 'Danny Kowalski',
      job: 'HVAC contractor',
      contact: '@dannybuilds',
    },
    budget: B(['free', 'free', 'free', 'ask']),
  },
  {
    displayName: 'Yuki Tanaka',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'quiet, exact, extremely funny in writing',
      interests: 'photography, cycling, coffee',
      area: 'Mountain View',
      goodSaturday: 'ride at dawn, shoot the same street corner again',
      hobbies: 'photographs one intersection every week, same time',
      tastes: 'ambient, Kawabata, pour over',
      lookingFor: 'someone patient with a slow starter',
      ageBand: 'early 30s',
      availability: 'weekends, weeknights are late',
      neighborhood: 'near Castro Street',
      dealbreakers: 'pressure to be someone louder',
      name: 'Yuki Tanaka',
      job: 'software engineer',
      contact: '@yukishoots',
    },
    budget: B(['free', 'ask', 'ask', 'never'], [], 2),
  },
  {
    displayName: 'Rebecca Stern',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'fast, funny, argues for sport and knows when to stop',
      interests: 'debate, tennis, cooking',
      area: 'Presidio Heights',
      goodSaturday: 'tennis at eight, then cooking something for six people',
      hobbies: 'coaches a high school debate team on weekends',
      tastes: 'Sondheim, Roth she has complicated feelings about, brisket',
      lookingFor: 'someone who can hold their own in an argument',
      ageBand: 'late 30s',
      availability: 'weeknights, Saturday mornings are coaching',
      neighborhood: 'near Laurel Village',
      dealbreakers: 'conflict avoidance',
      name: 'Rebecca Stern',
      job: 'litigator',
      contact: '@rebeccaargues',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['my firm'], 4),
  },
  {
    displayName: 'Ismail Toure',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'gentle, watchful, dry sense of humour',
      interests: 'football, tailoring, languages',
      area: 'Tenderloin',
      goodSaturday: 'match in the morning, then the shop until evening',
      hobbies: 'speaks five languages and is quietly learning a sixth',
      tastes: 'mbalax, Sembène, thieboudienne',
      lookingFor: 'someone patient and warm',
      ageBand: 'early 40s',
      availability: 'evenings, shop is open Saturdays',
      neighborhood: 'near Little Saigon',
      dealbreakers: 'snobbery about work',
      name: 'Ismail Toure',
      job: 'tailor',
      contact: '@ismailsews',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Clara Moretti',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'expressive, decisive, hates wasting time',
      interests: 'food writing, running, opera',
      area: 'North Beach',
      goodSaturday: 'run along the water, then eat somewhere and take notes',
      hobbies: 'writes a newsletter about restaurants she pays for herself',
      tastes: 'Puccini, Ferrante, anchovies on everything',
      lookingFor: 'someone with appetite, literal and otherwise',
      ageBand: 'mid 30s',
      availability: 'most evenings',
      neighborhood: 'near Washington Square',
      dealbreakers: 'picky eaters who are proud of it',
      name: 'Clara Moretti',
      job: 'food writer',
      contact: '@claraeats',
    },
    budget: B(['free', 'free', 'ask', 'ask'], [], 4),
  },
  {
    displayName: 'Victor Nguyen',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'calm, funny, unbothered by most things',
      interests: 'fishing, poker, cooking',
      area: 'San Jose',
      goodSaturday: 'out on the water at five, poker at eight',
      hobbies: 'has a spreadsheet of poker results going back six years',
      tastes: 'boom bap, Nguyen, phở from one place only',
      lookingFor: 'someone easy to be around',
      ageBand: 'late 30s',
      availability: 'weekends, weeknights variable',
      neighborhood: 'Willow Glen',
      dealbreakers: 'drama for its own sake',
      name: 'Victor Nguyen',
      job: 'dentist',
      contact: '@victorfishes',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Anouk Visser',
    fields: {
      gender: 'woman',
      seeking: 'women',
      vibe: 'direct to the point of bluntness, very kind underneath',
      interests: 'cycling, design, sailing',
      area: 'Dogpatch',
      goodSaturday: 'ride, then the studio, then somewhere with a view',
      hobbies: 'designs bicycle frames nobody has commissioned',
      tastes: 'minimal techno, Dutch design books, licorice',
      lookingFor: 'someone who says the real thing on the first try',
      ageBand: 'early 30s',
      availability: 'weekdays flexible, weekends are riding',
      neighborhood: 'near Third Street',
      dealbreakers: 'hinting instead of saying',
      name: 'Anouk Visser',
      job: 'industrial designer',
      contact: '@anoukrides',
    },
    budget: B(['free', 'free', 'ask', 'ask'], [], 4),
  },
  {
    displayName: 'Malik Johnson',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'thoughtful, funny, a good listener and knows it',
      interests: 'jazz, teaching, basketball',
      area: 'West Oakland',
      goodSaturday: 'record shop, then the court, then a set somewhere',
      hobbies: 'plays upright bass badly and refuses to stop',
      tastes: 'Mingus, Coates, po boys',
      lookingFor: 'someone with patience for a slow week',
      ageBand: 'mid 30s',
      availability: 'evenings, Saturdays are open',
      neighborhood: 'near Mandela Parkway',
      dealbreakers: 'dismissiveness about teaching as a career',
      name: 'Malik Johnson',
      job: 'middle school teacher',
      contact: '@malikbass',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Sofia Delgado',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'vivid, generous, occasionally overcommits',
      interests: 'salsa, public health, markets',
      area: 'Concord',
      goodSaturday: 'market in the morning, dancing at night',
      hobbies: 'dances salsa four nights a week and teaches on Tuesdays',
      tastes: 'Celia Cruz, García Márquez, tamales her aunt makes',
      lookingFor: 'someone who will learn one dance, badly, for her',
      ageBand: 'early 30s',
      availability: 'evenings except Tuesday',
      neighborhood: 'near Todos Santos',
      dealbreakers: 'refusing to try anything new in public',
      name: 'Sofia Delgado',
      job: 'epidemiologist',
      contact: '@sofiadances',
    },
    budget: B(['free', 'free', 'ask', 'ask'], [], 4),
  },
  {
    displayName: 'Arjun Kapoor',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'droll, observant, allergic to hype',
      interests: 'cricket, cooking, long-form journalism',
      area: 'Sunnyvale',
      goodSaturday: 'watch a match, cook all afternoon, read until late',
      hobbies: 'has read every New Yorker cover to cover since 2018',
      tastes: 'ghazals, Naipaul he argues with, dal done slowly',
      lookingFor: 'someone unimpressed by titles',
      ageBand: 'mid 30s',
      availability: 'evenings, weekends mostly free',
      neighborhood: 'near Murphy Avenue',
      dealbreakers: 'status-seeking',
      name: 'Arjun Kapoor',
      job: 'hardware engineer',
      contact: '@arjunreads',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Nina Petrov',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'cool at first, extremely warm once she decides',
      interests: 'climbing, tattooing, motorcycles',
      area: 'Bernal Heights',
      goodSaturday: 'climb, then the shop, then a ride if it is clear',
      hobbies: 'tattoos hand-poked work on friends and only friends',
      tastes: 'post-punk, Bulgakov, dark rum',
      lookingFor: 'someone unbothered by how she looks on paper',
      ageBand: 'early 30s',
      availability: 'afternoons and evenings',
      neighborhood: 'near Cortland',
      dealbreakers: 'wanting her to tone it down',
      name: 'Nina Petrov',
      job: 'tattoo artist',
      contact: '@ninapokes',
    },
    budget: B(['free', 'free', 'ask', 'never']),
  },
  {
    displayName: 'Gabriel Santos',
    fields: {
      gender: 'man',
      seeking: 'men',
      vibe: 'sunny, unhurried, harder to read than he seems',
      interests: 'capoeira, cooking, gardening',
      area: 'Richmond, East Bay',
      goodSaturday: 'roda in the morning, garden after, feed people at night',
      hobbies: 'grows chillies he is too scared to eat',
      tastes: 'samba, Amado, feijoada that takes a day',
      lookingFor: 'someone who shows up',
      ageBand: 'late 30s',
      availability: 'weekends, weeknights after 7',
      neighborhood: 'near Point Richmond',
      dealbreakers: 'flakiness',
      name: 'Gabriel Santos',
      job: 'physical therapist',
      contact: '@gabrielroda',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Esther Cohen',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'sharp, funny, no time for nonsense and says so warmly',
      interests: 'ceramics, hiking, history podcasts',
      area: 'Rockridge',
      goodSaturday: 'a trail before it gets hot, studio after',
      hobbies: 'makes mugs with deliberately uneven handles',
      tastes: 'klezmer, Ozick, babka she is picky about',
      lookingFor: 'someone secure enough to be teased',
      ageBand: 'late 30s',
      availability: 'evenings, weekends flexible',
      neighborhood: 'near College Avenue',
      dealbreakers: 'fragile egos',
      name: 'Esther Cohen',
      job: 'therapist',
      contact: '@estherclay',
    },
    budget: B(['free', 'free', 'ask', 'never'], ['my clients']),
  },
  {
    displayName: 'Ravi Deshmukh',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'enthusiastic, slightly scattered, deeply loyal',
      interests: 'trains, photography, street food',
      area: 'Foster City',
      goodSaturday: 'ride somewhere by rail with no destination',
      hobbies: 'has photographed every Caltrain station, twice',
      tastes: 'Bollywood soundtracks unironically, Rushdie, vada pav',
      lookingFor: 'someone game for a pointless adventure',
      ageBand: 'early 30s',
      availability: 'weekends, weeknights after 8',
      neighborhood: 'near the lagoon',
      dealbreakers: 'needing every outing to have a purpose',
      name: 'Ravi Deshmukh',
      job: 'transit planner',
      contact: '@ravirails',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
  {
    displayName: 'Camille Laurent',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'poised, wry, does not perform enthusiasm she does not feel',
      interests: 'wine, cycling, translation',
      area: 'Russian Hill',
      goodSaturday: 'a ride, then a long lunch that becomes dinner',
      hobbies: 'translates poetry nobody has asked her to translate',
      tastes: 'chanson, Ernaux, Jura wines',
      lookingFor: 'someone comfortable with a long silence',
      ageBand: 'early 40s',
      availability: 'weeknights, weekends variable',
      neighborhood: 'near Hyde Street',
      dealbreakers: 'small talk that never ends',
      name: 'Camille Laurent',
      job: 'literary translator',
      contact: '@camilletrans',
    },
    budget: B(['free', 'ask', 'ask', 'ask'], [], 2),
  },
  {
    displayName: 'Jamal Whitaker',
    fields: {
      gender: 'man',
      seeking: 'women',
      vibe: 'steady, funny, the person everyone calls in a crisis',
      interests: 'woodworking, boxing, cooking',
      area: 'San Leandro',
      goodSaturday: 'gym early, shop all afternoon, cook for whoever',
      hobbies: 'builds furniture for friends and refuses payment',
      tastes: 'neo soul, Whitehead, gumbo he argues about',
      lookingFor: 'someone who wants a partner, not an audience',
      ageBand: 'late 30s',
      availability: 'evenings, weekends open',
      neighborhood: 'near Marina Boulevard',
      dealbreakers: 'keeping score',
      name: 'Jamal Whitaker',
      job: 'firefighter',
      contact: '@jamalbuilds',
    },
    budget: B(['free', 'free', 'ask', 'ask'], ['my station']),
  },
  {
    displayName: 'Ingrid Larsen',
    fields: {
      gender: 'woman',
      seeking: 'men',
      vibe: 'crisp, dry, unexpectedly soft about animals',
      interests: 'skiing, epidemiology, crime novels',
      area: 'Menlo Park',
      goodSaturday: 'a long walk with the dog and a bad novel',
      hobbies: 'fosters elderly dogs nobody else wants',
      tastes: 'Nordic noir, Mankell, filter coffee',
      lookingFor: 'someone kind to animals and honest with people',
      ageBand: 'early 40s',
      availability: 'evenings, weekends flexible',
      neighborhood: 'near Sharon Heights',
      dealbreakers: 'impatience with old or slow creatures, of any species',
      name: 'Ingrid Larsen',
      job: 'biostatistician',
      contact: '@ingriddogs',
    },
    budget: B(['free', 'free', 'ask', 'ask']),
  },
];
